name: Build CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  EXILED_REFERENCES_URL: https://www.exiled.host/build_deps/Master.zip
  EXILED_REFERENCES_PATH: ${{ github.workspace }}/References

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - uses: actions/checkout@v2.3.4
      
      - name: Get references
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri ${{ env.EXILED_REFERENCES_URL }} -OutFile ${{ github.workspace }}/References.zip
          Expand-Archive -Path References.zip -DestinationPath ${{ env.EXILED_REFERENCES_PATH }}
        
      - name: Build
        env:
          EXILED_REFERENCES: ${{ env.EXILED_REFERENCES_PATH }}
        shell: pwsh
        run: |
          dotnet build /p:Configuration="Release" /p:Platform="Any CPU"
          
      - name: Publish win
        shell: pwsh
        run: |
          dotnet publish --runtime win10-x64 --self-contained true --framework net6.0 --configuration Release -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true DBAPI/DBAPI.csproj
      - name: Publish linux
        shell: pwsh
        run: |
          dotnet publish --runtime linux-x64 --self-contained true --framework net6.0 --configuration Release -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true DBAPI/DBAPI.csproj
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "${{ github.event.head_commit.message }} - ${{ github.sha }}"
          tag_name: "${{ github.run_id }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            "DBAPI/bin/Release/net6.0/win10-x64/publish/DBAPI.exe"
            "DBAPI/bin/Release/net6.0/linux-x64/publish/DBAPI"
            "DBAPI.Library/bin/Release/DBAPI.Library.dll"
